"""create_pet_model

Revision ID: 2fbdd2761d49
Revises: d1252175c146
Create Date: 2022-12-16 10:38:06.179132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2fbdd2761d49"
down_revision = "d1252175c146"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
