"""modify_token_model

Revision ID: 30793e2dad11
Revises: 32fa734d7234
Create Date: 2022-12-16 10:59:45.462065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "30793e2dad11"
down_revision = "32fa734d7234"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("Token")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Token",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('\"Token_id_seq\"'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="Token_pkey"),
    )
    op.drop_table("token")
    # ### end Alembic commands ###
