"""create_contract_model

Revision ID: 342bc3a79193
Revises: 30793e2dad11
Create Date: 2022-12-16 14:26:32.918079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "342bc3a79193"
down_revision = "30793e2dad11"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contract",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("token")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="token_pkey"),
    )
    op.drop_table("contract")
    # ### end Alembic commands ###
