"""create_token_model

Revision ID: 32fa734d7234
Revises: c3709afe22d5
Create Date: 2022-12-16 10:57:18.500337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "32fa734d7234"
down_revision = "c3709afe22d5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Token",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("pets")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pets",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="pets_pkey"),
    )
    op.drop_table("Token")
    # ### end Alembic commands ###
